### ISSUE TITLE
Lighthouse missing in your repo

### ISSUE THREAD

**Issue by B-Virtual** [ERS-HCL/generic-batch-processor#2]
Hi,

It seems lighthouse is missing in your repo. If I try to run the reactive demo, the project is referenced under Lighthouse\Lighthouse\Lighthouse.csproj but not present in the repo. What version are you using?

**Comment by vtthombre** [comment]
LightHouse is available in https://github.com/petabridge/lighthouse. 
The applicationuses 1.3.1 version
